### ISSUE TITLE
Show bundle size badge instead of install size

### ISSUE THREAD

**Issue by manniL** [jsless/defu#1]
5MB (install size) vs < 1 kB (bundle size) make a huge difference 📦 😋 

https://bundlephobia.com/result?p=defu@0.0.1

**Comment by pi0** [comment]
Yeah. I noticed that. However, bundle phobia is for browser bundles but defu is for Node.js. Maybe it is more realistic that we show actual "npm install" package size which included README and CHANGELOG. We can have both badges to indicate core is < 1kB :)
