### ISSUE TITLE
Couldn't transpile this module

### ISSUE THREAD

**Issue by amorino** [jsless/defu#2]
This module uses ES6 code which is problematic if the target is IE11, we can transpile it, however at the end of the lib file the module is exported as modules.export instead of default export which is problematic if we transpile it with Babel.

It should be default export to be consistent with the rest of the code (ES6).

**Comment by pi0** [comment]
Hi.
Target of defu is not either ES6 or esm. But CJS to support node >= 8.

**Comment by pi0** [comment]
ES5 compatibility has been improved in v0.0.4.
